version: "3.3"
services:
  ml-training:
    container_name: 'ml-training'
    command: bash -c "jupyter lab --notebook-dir=/home/ml-training --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    build: .
    ports:
      - '8888:8888'
    volumes:
      - ../ml-training:/home/ml-training
